SELECT ART.NOME_ARTISTA AS artista, ALB.NOME_ALBUM AS album
FROM ARTISTA AS ART
INNER JOIN ALBUM AS ALB
  ON ALB.ID_ARTISTA = ART.IDARTISTA
WHERE NOME_ARTISTA = 'Walter Phoenix'
ORDER BY ALB.NOME_ALBUM ASC;
