SELECT
  U.NOME_USUARIO AS usuario,
  COUNT(H.ID_CANCOES) AS qtde_musicas_ouvidas,
  ROUND(SUM(C.DURACAO/60), 2) AS total_minutos
FROM USUARIO AS U
INNER JOIN HISTORICO AS H
  ON H.ID_USUARIO = U.IDUSUARIO
INNER JOIN CANCOES AS C
  ON C.IDCANCOES = H.ID_CANCOES
GROUP BY U.NOME_USUARIO
ORDER BY U.NOME_USUARIO;
