SELECT
  COUNT(DISTINCT C.NOME_CANCAO) AS cancoes,
  COUNT(DISTINCT A.NOME_ARTISTA) AS artistas,
  COUNT(DISTINCT AB.NOME_ALBUM) AS albuns
FROM CANCOES AS C
INNER JOIN ARTISTA AS  A
INNER JOIN ALBUM AS AB;
