SELECT ART.NOME_ARTISTA AS artista, ALB.NOME_ALBUM AS album, COUNT(S.ID_ARTISTA) AS seguidores
FROM ARTISTA AS ART
INNER JOIN ALBUM AS ALB
  ON ALB.ID_ARTISTA = ART.IDARTISTA
INNER JOIN SEGUIDOR AS S
  ON ALB.ID_ARTISTA = S.ID_ARTISTA
GROUP BY album, artista
ORDER BY seguidores DESC, artista ASC, album ASC;
