SELECT U.NOME_USUARIO AS usuario,
CASE 
  WHEN MAX(YEAR(H.DATA_REPRODUCAO)) = 2021 THEN 'Usuário ativo'
  Else 'Usuário inativo'
END AS condicao_usuario
FROM USUARIO AS U
INNER JOIN HISTORICO AS H
  ON U.IDUSUARIO = H.ID_USUARIO
GROUP BY U.NOME_USUARIO;
